C Based on BILCAL, VERSION 3.0, AUGUST 1995
C
C Alexey Nikolayevich Petrov
C SINP MSU Russia
C gluk@srd.sinp.msu.ru
C
C*****************************************************************
      INTEGER       INFILE,OUTFILE
      REAL          YEAR,HEIGHT
      REAL          LATI,LONGI,MR,MLAT,MLONG
      REAL          XMAG,YMAG,ZMAG,COLAT,XLON
      CHARACTER*11  OUTFILENAME
      CHARACTER*11  INFILENAME      
      LOGICAL       VAL
      DIMENSION     VARE(4),VARB(4)
      COMMON/GENER/ UMR,ERA,AQUAD,BQUAD
C
      DATA LATI,LONGI,HEIGHT,YEAR
     &                  /45.1,293.1,100,1985.5/
c### year limit modified
      DATA VARB         /-90.0,-360.0,0.00000,1940.0/
      DATA VARE         /+90.0,+360.0,30000.0,2010.0/
C
      CALL INITIZE

      MONITOR=6
      OUTFILE=16
      INFILE=17

      WRITE(MONITOR, *) 'TYPE INPUT FILE NAME: '
      READ '(13A)', INFILENAME
      WRITE(MONITOR, *) 'INFILENAME=', INFILENAME
      
      WRITE(MONITOR, *) 'TYPE RESULT FILE NAME: '
      READ '(13A)', OUTFILENAME      
      WRITE(MONITOR, *) 'OUTFILENAME=', OUTFILENAME
      
      OPEN(UNIT=OUTFILE,FILE=OUTFILENAME,
     &     STATUS='NEW',FORM='FORMATTED') 
      OPEN(UNIT=INFILE,FILE=INFILENAME,STATUS='OLD',
     &     FORM='FORMATTED',ERR=8000)     

      WRITE(OUTFILE,3910) 
3910  FORMAT(
     & '  YEAR      ALT    LON     LAT     DIMO   B/B0     B       B0',
     & '      B-NORTH  B-EAST',
     & '  B-DOWN    DIP    DEC  L-VALUE MLONG  MLAT  C')  
      
1000  READ(INFILE, *, END=9999) YEAR, HEIGHT, LATI, LONGI
     
      CALL FELDCOF(YEAR,DIMO)
      CALL FELDG(LATI,LONGI,HEIGHT,BNORTH,BEAST,BDOWN,BABS)
      CALL SHELLG(LATI,LONGI,HEIGHT,DIMO,XL,ICODE,BAB1)
C      CALL GGM(0,LONGI,LATI,MLONG,MLAT)
      COLAT=(90.0 - LATI) * 0.01745329
      XLON=LONGI * 0.01745329
      CALL SPHCAR(HEIGHT,COLAT,XLON,XGEO,YGEO,ZGEO,1)
      CALL GEOMAG(XGEO,YGEO,ZGEO,XMAG,YMAG,ZMAG,1,YEAR)
      CALL SPHCAR(MR,MLAT,MLONG,XMAG,YMAG,ZMAG,-1)
      MLAT = 90 - MLAT/0.01745329
      MLONG = MLONG/0.01745329

      BEQU=DIMO/(XL*XL*XL)
      BDEL=1.E-3
      CALL FINDB0(0.05,BDEL,VAL,BEQ,RR0)
      IF(VAL) BEQU=BEQ
      DIP=ASIN(BDOWN/BABS)/UMR
      DEC=ASIN(BEAST/SQRT(BEAST*BEAST+BNORTH*BNORTH))/UMR
      BBX=BABS/BEQU
      IF(BBX.GT.9999.999) BBX=9999.999
      WRITE(OUTFILE,7177) YEAR,HEIGHT,LONGI,LATI,DIMO,BBX,BABS,BEQU,
     &      BNORTH,BEAST,BDOWN,DIP,DEC,XL,MLONG,MLAT,ICODE           
7177  FORMAT(F8.1,F8.1,F8.2,F8.2,F8.4,F9.3,
     &      (1X,F7.5),(1X,F7.5),3(1X,F7.5),
     &      2F7.1,F8.3,F8.2,F8.2,I3)
      GOTO 1000
8000  WRITE(MONITOR, *) 'INPUT FILE NOT FOUND'    
9999  STOP
      END
